# Generated by Django 3.1.5 on 2021-01-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(),
        ),
    ]
